version: '3.8'

x-env-variables: &env-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: machina_labs
  REACT_APP_SERVER_PORT: 3000

services:
  db:
    # to allow support for Apple M1 Chip machines
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      <<: *env-variables
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./frontend
    environment:
      <<: *env-variables
      NODE_PATH: src
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./frontend/src:/app/src
    links:
      - backend
    command: npm run dev
  backend:
    build: ./backend
    depends_on:
      - db
    expose:
      - 3000
    environment:
      <<: *env-variables
      MYSQL_HOST_IP: db
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    links:
      - db
    command: npm start